title: International Press journal MCGD author support
description: TeX related material for the manuscript preparation for the
             International Press journal Mathematics, Computation and Geometry of Data (MCGD)
show_downloads: true
theme: jekyll-theme-tactile
